#Optionally add your own date, else if you leave "None", today's date will be used:
#Must conform to ISO 8601
"datePublished": "None"

#Run name: this is the value of "-n" to the "run_wf.sh" script
"run_parameter": ""

#This is the URL to the MetaGOflow Version RO-Crate - the ro-crate containing
#the metadata describing the version of MetaGOflow used to generate these data
"metagoflow_version": "https://github.com/emo-bon/MetaGOflow/issues/53"

#Missing files - if a mandatory file is missing, but you still want to build a
#ro-crate, specify file paths here as a list of strings:
#e.g. ["krona.html", "DBB.merged_SSU.fasta.mseq.gz"]
"missing_files" : []

